### ISSUE TITLE
Is this component necessary for application using jgroups deployed on Kubernetes?

### ISSUE THREAD

**Issue by tjliupeng** [jgroups-extras/jgroups-kubernetes#13] opened 2016-10-14 02:59 UTC
Hi,

At present we try to move our application which uses JGroups to manage the cluster to Kubernetes. The JGroups uses UDP to communicate. Than we find that on the k8s env, the nodes can not communicate to each other. Each node forms a group. Does this component solve this problem? Can we solve the problem using TCP?

**Comment by slaskawi** [comment] 2016-10-14 05:49
Hey @tjliupeng !

Yes, that is correct. 

`TCP` is a transport protocol but JGroups also need a [discovery protocol](http://www.jgroups.org/manual-3.x/html/protlist.html#DiscoveryProtocols) to detect other nodes. `KUBE_PING` has been designed to solve discovery problem in OpenShift and Kubernetes. 

Thanks
Sebastian

**Comment by tjliupeng** [comment] 2016-10-14 09:53
Any example to use this library for the application embedding Jgroups components?

Thanks

**Comment by slaskawi** [comment] 2016-10-14 10:00
Infinispan provides `KUBE_PING` integration (https://github.com/infinispan/infinispan-simple-tutorials/tree/master/kubernetes). However you will probably be the most interested in configuration file, which can be found here: https://github.com/infinispan/infinispan/blob/master/cloud/src/main/resources/default-configs/default-jgroups-kubernetes.xml

Using Gossip Router in Kubernetes should also do the job. Take a look at this blog post for details: http://blog.infinispan.org/2015/03/infinispan-on-openshift-v3.html

**Comment by tjliupeng** [comment] 2016-10-14 10:02
@slaskawi , Thanks. I will read them and get back here.

**Comment by tjliupeng** [comment] 2016-10-21 07:55
@slaskawi , I succeuss to enable the TCP capability for Jgroups cluster in our application. Thanks for your help.

**Comment by ramakrishna90** [comment] 2018-02-01 10:03
in kubernetes version 1.8 it is giving 403 error when the kube_ping pings the kube api server. What can we do for this, we are using 0.9.3 version of the jgroups kubernetes discovery api, because the jgroups core api version is 3.6.11

**Comment by slaskawi** [comment] 2018-02-02 11:29
I'm not sure exactly what the problem is but getting `403` usually means permission problems. You need to make sure that your Pod has `view` permissions. In OpenShift for example you need execute additional commands (see [this manual entry](https://github.com/jgroups-extras/jgroups-kubernetes/tree/stable#running-inside-of-openshift)). My intuition tells me that you will also need it for Kubernetes.

**Comment by ramakrishna90** [comment] 2018-02-02 13:16
Sorry everyone,
I got the issue solved, We need to enable role binding in kubernetes where the service account for the namespace must be given the pod list get permissions

**Comment by slaskawi** [comment] 2018-02-02 13:19
Great! I'm glad you solved the issue.. Closing.

**Closed by slaskawi** 2018-02-02 13:19 UTC
